name: CI

on: [ push, pull_request ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry==1.7.1
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.5
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v27
      - name: Check Nix installation
        run: |
          nix build --version
          mkdir -p $HOME/.config/nix
          echo "experimental-features = nix-command flakes" > $HOME/.config/nix/nix.conf
      - name: Configure Nix
        run: |
          # nix-env --install --file '<nixpkgs>' --attr nix cacert -I nixpkgs=channel:nixpkgs-stable
          nix registry add nixpkgs github:NixOS/nixpkgs/nixos-21.05
          nix registry pin github:NixOS/nixpkgs/nixos-21.05
          nix build --no-link nixpkgs#glibc
          nix build --no-link nixpkgs#hello
      - name: Run ruff linter
        run: poetry run ruff check
      - name: Run McCabe complexity test
        run: poetry run ruff check --select C901
      - name: Run pytest
        run: poetry run pytest
